---
engines:
  pytest:
    exclude_paths:
      # This is actually a shell script
      - "src/bin/microsoft_teams.py"
  prospector:
    exclude_paths:
      # This is actually a shell script
      - "src/bin/microsoft_teams.py"
