name: Package Sensu Asset

on:
  workflow_dispatch:


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          cd src
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt --target lib
          ls -l
      - name: Create archive
        run: |
          cd src
          tar -cvzf ../sensu-microsoft-teams-handler-${{ github.ref_name }}-linux-amd64.tar.gz .
      - name: shasum
        run: shasum -a 512 sensu-microsoft-teams-handler-${{ github.ref_name }}-linux-amd64.tar.gz > sensu-microsoft-teams-handler-${{ github.ref_name }}-sha512-checksums.txt

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: upload artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sensu-microsoft-teams-handler-${{ github.ref_name }}-linux-amd64.tar.gz
            sensu-microsoft-teams-handler-${{ github.ref_name }}-sha512-checksums.txt
